-- DLP Platform Database Initialization Script
-- This script creates an initial admin user for the system
--
-- Note: The password is set by the backend (DataInitializer) on startup.
-- Default password: Opgg-58147321
-- Override via ADMIN_PASSWORD environment variable (maps to security.admin.password)
--
-- This is an Argon2id hash generated by the PasswordUtil class
-- You should change this password immediately after first login

-- Initial Admin User
INSERT INTO users (
    account_id,
    email,
    full_name,
    hashed_password,
    department,
    position,
    mfa_enabled,
    first_login,
    password_change_required,
    account_enabled,
    account_locked,
    login_attempts,
    password_changed_at,
    password_expiry_date,
    created_at,
    updated_at
) VALUES (
    'admin',
    'admin@dlp-platform.local',
    'System Administrator',
    '$argon2id$v=19$m=65536,t=3,p=4$placeholder_salt_value$placeholder_hash_value',
    'IT Department',
    'System Administrator',
    false,
    true,
    true,
    true,
    false,
    0,
    NOW(),
    NOW() + INTERVAL '30 days',
    NOW(),
    NOW()
) ON CONFLICT (account_id) DO NOTHING;

-- Insert Admin Role for the admin user
INSERT INTO user_roles (user_id, role)
SELECT u.id, 'ADMIN'
FROM users u
WHERE u.account_id = 'admin'
ON CONFLICT DO NOTHING;

-- Create indexes for better performance (if not already created by JPA)
CREATE INDEX IF NOT EXISTS idx_users_account_id ON users(account_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON audit_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_logs_ip_address ON audit_logs(ip_address);

-- Insert welcome audit log
INSERT INTO audit_logs (
    user_id,
    account_id,
    action,
    category,
    result,
    details,
    ip_address,
    user_agent,
    timestamp
)
SELECT
    u.id,
    'admin',
    'SYSTEM_INIT',
    'SYSTEM',
    'SUCCESS',
    'Database initialized with admin user',
    '127.0.0.1',
    'System',
    NOW()
FROM users u
WHERE u.account_id = 'admin'
ON CONFLICT DO NOTHING;

-- Display initialization message
DO $$
BEGIN
    RAISE NOTICE '================================================';
    RAISE NOTICE 'DLP Platform Database Initialized Successfully';
    RAISE NOTICE '================================================';
    RAISE NOTICE 'Initial Admin Account:';
    RAISE NOTICE '  Account ID: admin';
    RAISE NOTICE '  Email: admin@dlp-platform.local';
    RAISE NOTICE '  Password: Opgg-58147321 (override via ADMIN_PASSWORD env var)';
    RAISE NOTICE '';
    RAISE NOTICE 'IMPORTANT SECURITY NOTICE:';
    RAISE NOTICE '  1. You must change the admin password on first login';
    RAISE NOTICE '  2. You must enable MFA for the admin account';
    RAISE NOTICE '  3. Password is set by backend DataInitializer on startup';
    RAISE NOTICE '================================================';
END $$;
